/* ============================================================
   MACH 25 — ARCHIVE DATA
   Every figure cross-checked 27 Sep 2026 against Wikipedia,
   NASA / ESA / JAXA / Roscosmos / CNSA / ISRO, manufacturer
   pages, Spaceflight Now and Jonathan McDowell's statistics.
   Raw research: data/launch-vehicles.json, data/launch_schedule_research.json
   ============================================================ */

const ROCKETS = [
  {
    id: 'v-2', short: 'V-2', name: 'V-2 (A-4)', operator: 'German Army · Peenemünde', country: 'Germany',
    firstFlight: '1942-10-03', status: 'retired', firstFlightNote: 'First successful flight, Peenemünde Test Stand VII',
    height: 14.0, diameter: 1.65, mass: 12500, stages: 1,
    payloadLEO: null, payloadGTO: null, payloadMoon: null,
    thrustKN: 245, engines: '1× A-4 engine (Walter Thiel design)', engineCount: 1,
    propellant: 'LOX + ethanol (75/25 water mix)', reusable: false, costPerKgLEO: null,
    successes: null, failures: null, partialFailures: null,
    tagline: 'The first machine to touch space.',
    notes: 'The world’s first long-range guided ballistic missile and the first human-made object to cross the Kármán line — peak altitude ~88 km, range ~320 km. It carried a 1,000 kg warhead rather than an orbital payload, and its turbopump-fed, regeneratively-cooled engine set the architecture for every large liquid rocket that followed.',
    visual: { nose: 'cone', bodyColor: '#c9ccd1', accent: '#3a3f44', boosterCount: 0, finStyle: 'fins', stageHeights: [12.5, 1.5], stageDiameters: [1.65, 1.65], finSpan: 3.56, distinct: 'black-bands' },
  },
  {
    id: 'sputnik-8k71ps', short: 'R-7 / SPUTNIK', name: 'Sputnik 8K71PS', operator: 'OKB-1 (Sergei Korolev)', country: 'Soviet Union',
    firstFlight: '1957-10-04', status: 'retired', firstFlightNote: 'Launched Sputnik 1',
    height: 30.0, diameter: 2.99, mass: 267000, stages: 2,
    payloadLEO: 500, payloadGTO: null, payloadMoon: null,
    thrustKN: 3886, engines: '4× RD-107 + 1× RD-108', engineCount: 5,
    propellant: 'LOX + RP-1', reusable: false, costPerKgLEO: null,
    successes: 2, failures: 0, partialFailures: 0,
    tagline: 'The machine that opened the Space Age.',
    notes: 'An orbital derivative of the R-7 Semyorka ICBM: all five engines ignite on the pad and the four tapered strap-on boosters drop away after about 120 seconds. It flew only twice — Sputnik 1 and Sputnik 2 — but those two flights began the Space Age.',
    visual: { nose: 'cone', bodyColor: '#b0b4b8', accent: '#a3121a', boosterCount: 4, boosterShape: 'conical', finStyle: 'fins', stageHeights: [19.2, 28.0, 2.0], stageDiameters: [2.68, 2.95, 2.99], distinct: 'white-stack' },
  },
  {
    id: 'saturn-v', short: 'SATURN V', name: 'Saturn V', operator: 'NASA', country: 'United States',
    firstFlight: '1967-11-09', status: 'retired', firstFlightNote: 'Apollo 4 (uncrewed)',
    height: 110.6, diameter: 10.1, mass: 2970000, stages: 3,
    payloadLEO: 140000, payloadGTO: null, payloadMoon: 48600,
    thrustKN: 34020, engines: '5× Rocketdyne F-1', engineCount: 5,
    propellant: 'RP-1 + LOX', reusable: false, costPerKgLEO: 8400,
    successes: 12, failures: 0, partialFailures: 1,
    tagline: 'The machine that carried humans off Earth.',
    notes: 'Still the tallest, heaviest and most successful heavy-lift rocket ever flown: 13 launches, 12 clean successes, one partial failure (Apollo 6, two engines out early). TLI payload is quoted between 45,700 and 48,600 kg depending on mission; the Apollo 17-class figure is used here.',
    visual: { nose: 'ogive', bodyColor: '#e8e8e6', accent: '#e8b54d', boosterCount: 0, finStyle: 'fins', stageHeights: [42.0, 4.5, 24.9, 17.9, 6.6, 2.6, 2.6, 9.5], stageDiameters: [10.1, 6.6, 6.6, 6.6, 3.9, 3.9, 1.0, 1.4], finSpan: 15.3, distinct: 'roll-pattern' },
  },
  {
    id: 'space-shuttle', short: 'SHUTTLE', name: 'Space Shuttle', operator: 'NASA', country: 'United States',
    firstFlight: '1981-04-12', status: 'retired', firstFlightNote: 'STS-1 Columbia — first crewed maiden flight',
    height: 56.1, diameter: 8.4, mass: 2041166, stages: 2,
    payloadLEO: 27500, payloadGTO: 3810, payloadMoon: null,
    thrustKN: 30250, engines: '2× SRB + 3× Rocketdyne RS-25', engineCount: 5,
    propellant: 'PBAN solid + LOX/LH2', reusable: true, costPerKgLEO: 54500,
    successes: 133, failures: 2, partialFailures: 0,
    tagline: 'A spaceplane strapped to a fuel tank.',
    notes: '135 flights over 30 years; Challenger and Columbia were the two losses. Two recoverable solid boosters, an expendable orange external tank feeding three RS-25s on the orbiter. Partial reusability never delivered the promised economics — fully burdened costs approached $1.5 billion per flight.',
    visual: { nose: 'shuttle', bodyColor: '#e8e6e0', accent: '#d4571f', boosterCount: 2, boosterShape: 'cylinder', finStyle: 'none', stageHeights: [45.5, 47.0, 37.2], stageDiameters: [3.7, 8.4, 8.4], distinct: 'foam-orange' },
  },
  {
    id: 'soyuz-2-1b', short: 'SOYUZ-2', name: 'Soyuz-2.1b', operator: 'Roscosmos · TsSKB-Progress', country: 'Russia',
    firstFlight: '2006-12-27', status: 'active', firstFlightNote: 'CoRoT — first flight of the 2.1b variant',
    height: 46.3, diameter: 2.95, mass: 312000, stages: 3,
    payloadLEO: 8670, payloadGTO: 3100, payloadMoon: 2350,
    thrustKN: 4147, engines: '4× RD-107A + 1× RD-108A', engineCount: 5,
    propellant: 'LOX + RP-1', reusable: false, costPerKgLEO: 5200,
    successes: 86, failures: 2, partialFailures: 0,
    tagline: 'The R-7 bloodline, six decades on.',
    notes: 'The 2.1b introduced the closed-cycle RD-0124 upper stage (~359 s Isp), adding roughly a tonne over the 2.1a. Through mid-2026 the variant has flown 88 times with 86 successes — the longest-lived rocket architecture in history, descended directly from the 1957 R-7.',
    visual: { nose: 'cone', bodyColor: '#c9ccd1', accent: '#a3121a', boosterCount: 4, boosterShape: 'conical', finStyle: 'fins', stageHeights: [19.6, 27.1, 6.7, 7.9], stageDiameters: [2.68, 2.95, 2.66, 3.0], distinct: 'white-stack' },
  },
  {
    id: 'atlas-v-551', short: 'ATLAS V', name: 'Atlas V 551', operator: 'United Launch Alliance', country: 'United States',
    firstFlight: '2002-08-21', status: 'active', firstFlightNote: 'Family debut 2002 (401); 551 first flew 2006',
    height: 58.3, diameter: 3.81, mass: 590000, stages: 2,
    payloadLEO: 18850, payloadGTO: 8900, payloadMoon: null,
    thrustKN: 12272, engines: '1× RD-180 + 5× AJ-60A', engineCount: 6,
    propellant: 'RP-1 + LOX · HTPB solids', reusable: false, costPerKgLEO: 10600,
    successes: 109, failures: 0, partialFailures: 1,
    tagline: 'A Russian engine on an American legend.',
    notes: 'The most powerful Atlas V: 5 m fairing, five solid strap-ons, single-engine Centaur. Family record through 2026 is 110 launches with no total failures. It launched Curiosity to Mars, New Horizons to Pluto — and is now retiring in favour of Vulcan.',
    visual: { nose: 'ogive', bodyColor: '#e6e8ea', accent: '#c8102e', boosterCount: 5, boosterShape: 'cylinder', boosterScale: 0.41, boosterHeight: 20.5, finStyle: 'none', stageHeights: [32.5, 10.0, 15.8], stageDiameters: [3.81, 3.05, 5.0], distinct: 'logo' },
  },
  {
    id: 'falcon-9-block-5', short: 'FALCON 9', name: 'Falcon 9 Block 5', operator: 'SpaceX', country: 'United States',
    firstFlight: '2018-05-11', status: 'active', firstFlightNote: 'Bangabandhu-1 — first flight of Block 5',
    height: 69.8, diameter: 3.7, mass: 549000, stages: 2,
    payloadLEO: 22800, payloadGTO: 8300, payloadMoon: null,
    thrustKN: 7600, engines: '9× SpaceX Merlin 1D', engineCount: 9,
    propellant: 'RP-1 + LOX', reusable: true, costPerKgLEO: 3200,
    successes: 632, failures: 1, partialFailures: 0,
    tagline: 'The rocket that made reuse routine.',
    notes: 'The most-flown orbital launch vehicle family in history: 633 Block 5 launches through mid-2026 at 99.8% success. Payloads are expendable-class maxima; typical reusable missions sacrifice several tonnes to fly the booster home.',
    visual: { nose: 'ogive', bodyColor: '#f2f2f0', accent: '#c8102e', boosterCount: 0, finStyle: 'grid-fins', stageHeights: [47.7, 13.8, 8.3], stageDiameters: [3.7, 3.7, 5.2], distinct: 'logo' },
  },
  {
    id: 'falcon-heavy', short: 'FALCON HEAVY', name: 'Falcon Heavy', operator: 'SpaceX', country: 'United States',
    firstFlight: '2018-02-06', status: 'active', firstFlightNote: 'Test flight — Tesla Roadster past Mars orbit',
    height: 70.0, diameter: 3.7, mass: 1420000, stages: 2,
    payloadLEO: 63800, payloadGTO: 26700, payloadMoon: 16800,
    thrustKN: 22820, engines: '27× SpaceX Merlin 1D', engineCount: 27,
    propellant: 'RP-1 + LOX', reusable: true, costPerKgLEO: 2400,
    successes: 14, failures: 0, partialFailures: 0,
    tagline: 'Three Falcons, one rocket.',
    notes: 'The highest-thrust rocket currently operational: 27 Merlins ignite in unison and both side boosters routinely fly back to the Cape. Payload figures are expendable maxima; reusable GTO capability is closer to ~8 t.',
    visual: { nose: 'ogive', bodyColor: '#f2f2f0', accent: '#c8102e', boosterCount: 2, boosterShape: 'cylinder', boosterScale: 1.0, boosterHeight: 42.6, finStyle: 'grid-fins', stageHeights: [42.6, 12.6, 13.2], stageDiameters: [3.7, 3.7, 5.2], distinct: 'logo' },
  },
  {
    id: 'electron', short: 'ELECTRON', name: 'Electron', operator: 'Rocket Lab', country: 'New Zealand / USA',
    firstFlight: '2017-05-25', status: 'active', firstFlightNote: '“It’s a Test” — reached space, not orbit',
    height: 18.0, diameter: 1.2, mass: 13000, stages: 2,
    payloadLEO: 300, payloadGTO: null, payloadMoon: null,
    thrustKN: 224.3, engines: '9× Rocket Lab Rutherford', engineCount: 9,
    propellant: 'RP-1 + LOX', reusable: false, costPerKgLEO: 25000,
    successes: 90, failures: 4, partialFailures: 0,
    tagline: 'Battery-pumped, 3D-printed, weekly.',
    notes: 'The first orbital-class rocket with electrically pumped engines — lithium-polymer batteries replace the turbopump — and the first privately developed rocket to reach orbit from the Southern Hemisphere. 94 orbital missions through mid-2026 on an all-composite black airframe.',
    visual: { nose: 'ogive', bodyColor: '#33383f', accent: '#f0f0ee', boosterCount: 0, finStyle: 'none', stageHeights: [12.1, 2.4, 3.5], stageDiameters: [1.2, 1.2, 1.2], distinct: 'logo' },
  },
  {
    id: 'vega-c', short: 'VEGA-C', name: 'Vega-C', operator: 'Arianespace · Avio · ESA', country: 'Europe',
    firstFlight: '2022-07-13', status: 'active', firstFlightNote: 'VV21 — LARES 2 and six CubeSats',
    height: 34.8, diameter: 3.0, mass: 210000, stages: 4,
    payloadLEO: 2300, payloadGTO: null, payloadMoon: null,
    thrustKN: 4323, engines: '1× P120C (solid first stage)', engineCount: 1,
    propellant: 'Solid HTPB/AP/Al', reusable: false, costPerKgLEO: 17000,
    successes: 5, failures: 1, partialFailures: 0,
    tagline: 'Europe’s all-solid small-lift stack.',
    notes: 'Three solid stages (P120C, Zefiro 40, Zefiro 9) plus a liquid AVUM+ fourth stage. The P120C is shared with Ariane 6 as a strap-on — one motor family, two rockets. Six launches, one failure (VV22, 2022).',
    visual: { nose: 'ogive', bodyColor: '#e8e8e6', accent: '#c9a15e', boosterCount: 0, finStyle: 'none', stageHeights: [13.9, 7.9, 3.5, 1.6, 8.0], stageDiameters: [3.0, 2.98, 2.94, 2.6, 2.8], distinct: 'black-bands' },
  },
  {
    id: 'lvm3', short: 'LVM3', name: 'LVM3 (GSLV Mk III)', operator: 'ISRO', country: 'India',
    firstFlight: '2014-12-18', status: 'active', firstFlightNote: 'Suborbital CARE test; orbital debut 5 Jun 2017',
    height: 43.43, diameter: 4.0, mass: 640000, stages: 3,
    payloadLEO: 10000, payloadGTO: 4200, payloadMoon: 3000,
    thrustKN: 11886, engines: '2× S200 + 2× Vikas + CE-20', engineCount: 4,
    propellant: 'Solid + hypergolic + cryogenic', reusable: false, costPerKgLEO: 4200,
    successes: 9, failures: 0, partialFailures: 0,
    tagline: 'India’s heaviest rocket — and Chandrayaan-3’s ride.',
    notes: 'Two 3.2 m S200 solids, a hypergolic L110 core, and an indigenous C25 cryogenic upper stage (442 s Isp). A perfect 9-for-9 record through late 2025, including the mission that put India on the Moon.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#e8623c', boosterCount: 2, boosterShape: 'cylinder', boosterScale: 0.8, boosterHeight: 25.75, finStyle: 'none', stageHeights: [21.4, 13.5, 10.75], stageDiameters: [4.0, 4.0, 5.0], distinct: 'flag' },
  },
  {
    id: 'long-march-5', short: 'LM-5', name: 'Long March 5', operator: 'CASC · CALT', country: 'China',
    firstFlight: '2016-11-03', status: 'active', firstFlightNote: 'CZ-5 maiden flight from Wenchang',
    height: 56.97, diameter: 5.0, mass: 851800, stages: 3,
    payloadLEO: 25000, payloadGTO: 14000, payloadMoon: 9000,
    thrustKN: 10634, engines: '8× YF-100 + 2× YF-77', engineCount: 10,
    propellant: 'LOX/RP-1 + LOX/LH2', reusable: false, costPerKgLEO: 8000,
    successes: 17, failures: 1, partialFailures: 0,
    tagline: 'China’s heavy-lift backbone.',
    notes: 'Four kerolox boosters around a 5 m hydrogen core with a YF-75D upper stage. 18 flights (11 CZ-5 + 7 CZ-5B) with one failure (2017) — the vehicle behind Tianhe, Chang’e 5 and Tianwen-1.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#c8102e', boosterCount: 4, boosterShape: 'cylinder', boosterScale: 0.67, boosterHeight: 26.0, finStyle: 'none', stageHeights: [33.2, 11.5, 12.0], stageDiameters: [5.0, 5.0, 5.0], distinct: 'flag' },
  },
  {
    id: 'h3', short: 'H3', name: 'H3 (H3-24L)', operator: 'JAXA · Mitsubishi Heavy Ind.', country: 'Japan',
    firstFlight: '2023-03-07', status: 'active', firstFlightNote: 'TF1 test flight failed at second-stage ignition',
    height: 63.0, diameter: 5.27, mass: 575000, stages: 2,
    payloadLEO: 16000, payloadGTO: 7900, payloadMoon: 6000,
    thrustKN: 12142, engines: '2× LE-9 + 4× SRB-3', engineCount: 6,
    propellant: 'LOX/LH2 + HTPB solid', reusable: false, costPerKgLEO: 2100,
    successes: 7, failures: 2, partialFailures: 0,
    tagline: 'Half the cost of the H-IIA.',
    notes: 'A modular hydrogen core with zero-to-four solid strap-ons, built to halve H-IIA launch costs. Figures are the maximum H3-24 configuration; nine flights through mid-2026 with seven successes after a failed maiden flight.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#c8102e', boosterCount: 2, boosterShape: 'cylinder', boosterScale: 0.47, boosterHeight: 15.0, finStyle: 'none', stageHeights: [37.0, 9.3, 16.0], stageDiameters: [5.27, 5.27, 5.2], distinct: 'logo' },
  },
  {
    id: 'ariane-6', short: 'ARIANE 6', name: 'Ariane 6 (A64)', operator: 'Arianespace · ESA · CNES', country: 'Europe',
    firstFlight: '2024-07-09', status: 'active', firstFlightNote: 'VA262 maiden flight (A62 config)',
    height: 63.0, diameter: 5.4, mass: 860000, stages: 2,
    payloadLEO: 21650, payloadGTO: 11500, payloadMoon: 8600,
    thrustKN: 20490, engines: '1× Vulcain 2.1 + 4× P120C', engineCount: 5,
    propellant: 'LOX/LH2 + HTPB solid', reusable: false, costPerKgLEO: 6700,
    successes: 8, failures: 0, partialFailures: 1,
    tagline: 'Europe’s sovereign route to orbit.',
    notes: 'A Vulcain 2.1 core with a restartable Vinci upper stage and two or four P120C strap-ons — the P120C being the largest solid motor ever built in Europe. Figures are the A64 maximum configuration; nine flights through mid-2026.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#1f3b66', boosterCount: 4, boosterShape: 'cylinder', boosterScale: 0.63, boosterHeight: 15.5, finStyle: 'none', stageHeights: [35.0, 9.5, 18.5], stageDiameters: [5.4, 5.4, 5.4], distinct: 'logo' },
  },
  {
    id: 'vulcan-centaur', short: 'VULCAN', name: 'Vulcan Centaur (VC6)', operator: 'United Launch Alliance', country: 'United States',
    firstFlight: '2024-01-08', status: 'active', firstFlightNote: 'VC2S — Peregrine Mission One',
    height: 61.6, diameter: 5.4, mass: 758000, stages: 2,
    payloadLEO: 27200, payloadGTO: 15300, payloadMoon: 12100,
    thrustKN: 17260, engines: '2× BE-4 + 6× GEM-63XL', engineCount: 8,
    propellant: 'Liquid methane + LOX · HTPB', reusable: false, costPerKgLEO: 4000,
    successes: 4, failures: 0, partialFailures: 0,
    tagline: 'Atlas’ methalox heir.',
    notes: 'ULA’s replacement for Atlas V: two BE-4 engines on a 5.4 m core, up to six GEM-63XL solids, and a Centaur V upper stage. Figures are the maximum VC6 configuration — the first American-built methalox engine to reach orbit.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#c8102e', boosterCount: 6, boosterShape: 'cylinder', boosterScale: 0.30, boosterHeight: 19.5, finStyle: 'none', stageHeights: [33.3, 12.6, 15.7], stageDiameters: [5.4, 5.4, 5.4], distinct: 'logo' },
  },
  {
    id: 'new-glenn', short: 'NEW GLENN', name: 'New Glenn', operator: 'Blue Origin', country: 'United States',
    firstFlight: '2025-01-16', status: 'active', firstFlightNote: 'NG-1 — reached orbit with Blue Ring Pathfinder',
    height: 98.0, diameter: 7.0, mass: 1400000, stages: 2,
    payloadLEO: 45000, payloadGTO: 13000, payloadMoon: null,
    thrustKN: 17000, engines: '7× Blue Origin BE-4', engineCount: 7,
    propellant: 'Liquid methane + LOX', reusable: true, costPerKgLEO: 1500,
    successes: 3, failures: 0, partialFailures: 1,
    tagline: 'Seven methalox engines, reusable booster.',
    notes: 'Blue Origin’s orbital debut after two decades of suborbital New Shepard — a 7-engine reusable first stage landing on a sea platform. NG-1 reached orbit in January 2025; NG-2 achieved the first booster landing in November 2025.',
    visual: { nose: 'ogive', bodyColor: '#3f618d', accent: '#f0f0ee', boosterCount: 0, finStyle: 'none', stageHeights: [57.0, 20.0, 21.0], stageDiameters: [7.0, 5.0, 5.0], distinct: 'logo' },
  },
  {
    id: 'sls-block-1', short: 'SLS', name: 'SLS Block 1', operator: 'NASA', country: 'United States',
    firstFlight: '2022-11-16', status: 'active', firstFlightNote: 'Artemis I uncrewed lunar flyby',
    height: 111.25, diameter: 8.4, mass: 2610000, stages: 2,
    payloadLEO: 95000, payloadGTO: null, payloadMoon: 27000,
    thrustKN: 39000, engines: '4× RS-25 + 2× five-segment SRB', engineCount: 6,
    propellant: 'LOX/LH2 + PBAN solid', reusable: false, costPerKgLEO: 26000,
    successes: 2, failures: 0, partialFailures: 0,
    tagline: 'Shuttle heritage, Moon-bound.',
    notes: 'The highest-thrust rocket ever to carry humans: two Shuttle-derived five-segment solids and four RS-25s on an 8.4 m core, with an ICPS upper stage. Two for two through mid-2026 — Artemis I and the crewed Artemis II.',
    visual: { nose: 'capsule', bodyColor: '#e8e6e0', accent: '#d4571f', boosterCount: 2, boosterShape: 'cylinder', boosterScale: 0.22, boosterHeight: 58.1, finStyle: 'none', escTower: true, stageHeights: [75.8, 6.45, 29.0], stageDiameters: [8.4, 5.0, 5.0], distinct: 'flag' },
  },
  {
    id: 'starship-super-heavy', short: 'STARSHIP', name: 'Starship · Super Heavy', operator: 'SpaceX', country: 'United States',
    firstFlight: '2023-04-20', status: 'in-development', firstFlightNote: 'IFT-1; 13 integrated flight tests through Jul 2026',
    height: 123.0, diameter: 9.0, mass: 4975000, stages: 2,
    payloadLEO: 100000, payloadGTO: null, payloadMoon: null,
    thrustKN: 80800, engines: '33× SpaceX Raptor 3', engineCount: 33,
    propellant: 'LOX + liquid methane', reusable: true, costPerKgLEO: 1000, costIsTarget: true,
    successes: 7, failures: 6, partialFailures: 0,
    tagline: 'The most powerful machine ever built.',
    notes: 'The largest and most powerful rocket ever flown — 33 methalox Raptors producing 80.8 MN, more than twice Saturn V. The 100 t LEO figure is a design target: through flight 13 the ship flew only suborbital profiles. The booster is caught out of the air by the launch tower.',
    visual: { nose: 'ogive', bodyColor: '#b8bcc2', accent: '#2b2f36', boosterCount: 0, finStyle: 'grid-fins', stageHeights: [62.0, 61.0], stageDiameters: [9.0, 9.0], distinct: 'stainless-silver' },
  },
  {
    id: 'neutron', short: 'NEUTRON', name: 'Neutron', operator: 'Rocket Lab', country: 'United States',
    firstFlight: null, status: 'in-development', firstFlightNote: 'Design target — maiden flight NET 2026',
    height: 42.8, diameter: 7.0, mass: 480000, stages: 2,
    payloadLEO: 13000, payloadGTO: null, payloadMoon: null,
    thrustKN: 6600, engines: '9× Rocket Lab Archimedes', engineCount: 9,
    propellant: 'LOX + liquid methane', reusable: true, costPerKgLEO: 3800, costIsTarget: true,
    successes: null, failures: null, partialFailures: null,
    tagline: 'The reusable mid-lift challenger.',
    notes: 'All figures are published design targets, not flight-proven numbers. A tapered 7 m carbon-composite first stage with nine staged-combustion Archimedes engines, designed for barge landings and 25 reuses; the “hungry hippo” fairing doors open to dispense satellites without jettisoning a fairing.',
    visual: { nose: 'ogive', bodyColor: '#33383f', accent: '#f0f0ee', boosterCount: 0, finStyle: 'none', stageHeights: [31.3, 11.5], stageDiameters: [7.0, 4.9], distinct: 'logo' },
  },
  {
    id: 'terran-r', short: 'TERRAN R', name: 'Terran R', operator: 'Relativity Space', country: 'United States',
    firstFlight: null, status: 'in-development', firstFlightNote: 'Design target — maiden flight NET 2026',
    height: 87.0, diameter: 5.4, mass: null, stages: 2,
    payloadLEO: 33500, payloadGTO: null, payloadMoon: null,
    thrustKN: 15560, engines: '13× Relativity Aeon R', engineCount: 13,
    propellant: 'LOX + liquid methane', reusable: true, costPerKgLEO: 1600, costIsTarget: true,
    successes: null, failures: null, partialFailures: null,
    tagline: 'Printed, reusable, methane.',
    notes: 'All figures are published design targets. A fully 3D-printed methalox vehicle — the largest metal-additive manufacturing programme ever attempted — targeting 20 flights per first stage and a 23.5 t reusable payload.',
    visual: { nose: 'ogive', bodyColor: '#e0e2e4', accent: '#1f3b66', boosterCount: 0, finStyle: 'none', stageHeights: [55.0, 14.0, 18.0], stageDiameters: [5.4, 5.4, 5.4], distinct: 'logo' },
  },
  {
    id: 'long-march-9', short: 'LM-9', name: 'Long March 9', operator: 'CASC · CALT', country: 'China',
    firstFlight: null, status: 'in-development', firstFlightNote: 'Design target — first flight NET 2033',
    height: 114.0, diameter: 10.6, mass: 4369000, stages: 3,
    payloadLEO: 150000, payloadGTO: null, payloadMoon: 54000,
    thrustKN: 60000, engines: '30× YF-215 (planned)', engineCount: 30,
    propellant: 'LOX + liquid methane', reusable: true, costPerKgLEO: null,
    successes: null, failures: null, partialFailures: null,
    tagline: 'China’s Starship-class ambition.',
    notes: 'All figures are published design targets for a 10.6 m methalox vehicle with a reusable first stage — 150 t to LEO, 54 t to the Moon — intended to support Chinese crewed lunar missions and a polar Moon base.',
    visual: { nose: 'ogive', bodyColor: '#e8e6e0', accent: '#c8102e', boosterCount: 0, finStyle: 'grid-fins', stageHeights: [64.0, 20.0, 15.0, 15.0], stageDiameters: [10.6, 10.6, 10.6, 15.0], distinct: 'flag' },
  },
];

/* visual profile lookup for the 3D rig */
const VISUALS = {};
ROCKETS.forEach((r) => { VISUALS[r.id] = r.visual; });

/* ============================================================
   LINEAGE — a century of firsts
   Dates verified 27 Sep 2026 via Wikipedia and NASA archives.
   ============================================================ */
const EVENTS = [
  { date: '1926-03-16', title: 'Goddard flies the first liquid rocket', era: 'Pioneers', vehicle: 'Nell', actor: 'Robert H. Goddard', kind: 'first', location: 'Auburn, Massachusetts', lat: 42.22, lon: -71.84, impact: 7,
    description: 'The world’s first liquid-fuelled rocket climbed just 12.5 m in 2.5 seconds — but every orbital rocket since is a descendant of that flight.' },
  { date: '1942-10-03', title: 'V-2 reaches space', era: 'WWII', vehicle: 'V-2', actor: 'von Braun team · Peenemünde', kind: 'first', location: 'Peenemünde Test Stand VII', lat: 54.68, lon: 13.73, impact: 9,
    description: 'V-4 reached about 85 km and flew 190 km — the first human-made object to touch the edge of space. Its engine, turbopump and gyro guidance invented the template every orbital rocket still follows.' },
  { date: '1945-07-20', title: 'Operation Paperclip established', era: 'Post-War', vehicle: null, actor: 'US Joint Chiefs of Staff', kind: 'milestone', location: null, impact: 8,
    description: 'More than 1,600 German scientists and engineers — including Wernher von Braun — were brought to the United States, seeding the programme that would build the Saturn V.' },
  { date: '1957-10-04', title: 'Sputnik 1', era: 'Space Race', vehicle: 'R-7 Semyorka', actor: 'USSR', kind: 'first', location: 'Baikonur Site 1/5', lat: 45.96, lon: 63.34, impact: 10,
    description: 'A 58 cm, 84 kg beeping sphere began orbiting every 96 minutes. Its radio signal started the Space Age — and the missile race of the Cold War.' },
  { date: '1957-11-03', title: 'Laika reaches orbit', era: 'Space Race', vehicle: 'R-7', actor: 'USSR', kind: 'first', location: 'Baikonur Site 1/5', lat: 45.96, lon: 63.34, impact: 7,
    description: 'A stray dog from Moscow became the first animal to orbit Earth, proving living beings could survive launch stresses. She had no return system.' },
  { date: '1958-01-31', title: 'Explorer 1 answers Sputnik', era: 'Space Race', vehicle: 'Juno I', actor: 'NASA / ABMA', kind: 'first', location: 'Cape Canaveral LC-26A', lat: 28.44, lon: -80.57, impact: 8,
    description: 'America’s first satellite discovered the Van Allen radiation belts — the first major scientific discovery of the space age, from a pencil-shaped probe 2,600 km up.' },
  { date: '1958-10-01', title: 'NASA begins operations', era: 'Space Race', vehicle: null, actor: 'NASA', kind: 'milestone', location: null, impact: 9,
    description: 'Created by Eisenhower with 8,000 inherited staff and a roughly $100 million budget — the agency that would put humans on the Moon eleven years later.' },
  { date: '1959-01-02', title: 'Luna 1 escapes Earth orbit', era: 'Space Race', vehicle: 'Luna 1 / 8K72', actor: 'USSR', kind: 'first', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 6,
    description: 'A 361 kg probe became the first spacecraft to escape Earth’s gravity and circle the Sun, missing the Moon by 6,000 km.' },
  { date: '1961-04-12', title: 'Gagarin orbits the Earth', era: 'Space Race', vehicle: 'Vostok-K', actor: 'Yuri Gagarin · USSR', kind: 'first', location: 'Baikonur Site 1/5', lat: 45.96, lon: 63.34, impact: 10,
    description: 'One orbit, 108 minutes, the first human in space. Gagarin ejected at 7 km and parachuted to Earth — a 27-year-old who never flew a fighter jet before that year.' },
  { date: '1961-05-05', title: 'Alan Shepard: first American in space', era: 'Space Race', vehicle: 'Mercury-Redstone 3', actor: 'Alan Shepard · NASA', kind: 'first', location: 'Cape Canaveral LC-5', lat: 28.51, lon: -80.56, impact: 8,
    description: 'A 15-minute suborbital hop to 187 km — and the first time a human controlled a spacecraft in flight, after a chimpanzee had flown the same profile months earlier.' },
  { date: '1962-02-20', title: 'John Glenn orbits Earth', era: 'Space Race', vehicle: 'Mercury-Atlas 6', actor: 'John Glenn · NASA', kind: 'first', location: 'Cape Canaveral LC-14', lat: 28.48, lon: -80.57, impact: 7,
    description: 'The first American to orbit Earth circled the globe three times in under five hours, on a rocket derived from an ICBM.' },
  { date: '1963-06-16', title: 'Tereshkova: first woman in space', era: 'Space Race', vehicle: 'Vostok-K', actor: 'Valentina Tereshkova · USSR', kind: 'first', location: 'Baikonur Site 1/5', lat: 45.96, lon: 63.34, impact: 8,
    description: 'A 26-year-old textile worker orbited Earth 48 times in just under three days — more time in space than every American astronaut combined at that point.' },
  { date: '1967-11-09', title: 'Saturn V first flight', era: 'Apollo', vehicle: 'Saturn V', actor: 'NASA', kind: 'first', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 9,
    description: 'Apollo 4 sent the full 110.6 m stack 19,000 km downrange — the first flight of the largest rocket ever built, and the first launch from Pad 39A.' },
  { date: '1968-12-21', title: 'Apollo 8 leaves Earth orbit', era: 'Apollo', vehicle: 'Saturn V', actor: 'NASA', kind: 'first', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 9,
    description: 'Three humans became the first to ride a rocket beyond Earth orbit. On Christmas Eve they read Genesis while watching Earth rise over the Moon.' },
  { date: '1969-02-21', title: 'N1 fails on the pad', era: 'Space Race', vehicle: 'N1', actor: 'USSR', kind: 'failure', location: 'Baikonur Site 110', lat: 45.92, lon: 63.40, impact: 7,
    description: 'The Soviet Moon rocket’s 30-engine first stage erupted into a fireball about 70 seconds after liftoff — the first of four launches, four explosions, that ended the Soviet crewed lunar programme.' },
  { date: '1969-07-16', title: 'Apollo 11 lifts off', era: 'Apollo', vehicle: 'Saturn V', actor: 'NASA', kind: 'launch', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 10,
    description: 'A 2,800-tonne Saturn V burned 15 tonnes of propellant per second to throw three astronauts toward the Moon. Four days later, 650 million people watched the first footprints in lunar dust.' },
  { date: '1969-07-20', title: 'Apollo 11 lands on the Moon', era: 'Apollo', vehicle: 'Lunar Module Eagle', actor: 'NASA', kind: 'first', location: 'Sea of Tranquility', impact: 10,
    description: 'Armstrong and Aldrin walked on another world six and a half hours after touchdown, leaving footprints that, with no wind to erase them, may outlast humanity.' },
  { date: '1970-09-12', title: 'Luna 16 returns Moon dust', era: 'Space Race', vehicle: 'Proton-K', actor: 'USSR', kind: 'first', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 6,
    description: 'The first robotic lunar sample return: 101 g of Moon soil delivered to Earth by a spacecraft that scooped it, launched it, and landed it autonomously.' },
  { date: '1971-04-19', title: 'Salyut 1: the first space station', era: 'Space Race', vehicle: 'Proton-K', actor: 'USSR', kind: 'first', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 8,
    description: 'The first orbital habitat — 15 m long, 18.9 t. Its first crew died during re-entry from a valve failure, but the station concept survived into Mir, the ISS and Tiangong.' },
  { date: '1977-08-12', title: 'Enterprise glides free', era: 'Shuttle Era', vehicle: 'Shuttle Enterprise', actor: 'NASA', kind: 'first', location: 'Edwards AFB', lat: 34.90, lon: -117.88, impact: 6,
    description: 'A crewed orbiter was released from the back of a 747 at 8,000 ft and glided for five minutes — proving the Shuttle could come home without engines.' },
  { date: '1977-09-05', title: 'Voyager 1 launches', era: 'Golden Age', vehicle: 'Titan IIIE-Centaur', actor: 'NASA', kind: 'launch', location: 'Cape Canaveral LC-41', lat: 28.50, lon: -80.60, impact: 9,
    description: 'A probe launched on a 12-year mission to Jupiter and Saturn has now run for 49 years — it left the solar system at 61,146 km/h and is still talking from over 25 billion km away.' },
  { date: '1981-04-12', title: 'STS-1: the Shuttle flies', era: 'Shuttle Era', vehicle: 'Space Shuttle Columbia', actor: 'NASA', kind: 'first', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 9,
    description: 'Exactly 20 years after Gagarin, Columbia became the first orbital vehicle to fly with a crew on its maiden flight — and the first winged machine to glide back from orbit.' },
  { date: '1986-01-28', title: 'Challenger', era: 'Shuttle Era', vehicle: 'Space Shuttle Challenger', actor: 'NASA', kind: 'failure', location: 'KSC LC-39B', lat: 28.61, lon: -80.60, impact: 9,
    description: 'A failed O-ring seal in the right solid booster, exposed by a freezing launch morning, destroyed the vehicle 73 seconds after liftoff. Seven crew lost; the fleet was grounded for 32 months.' },
  { date: '1986-02-20', title: 'Mir: the first modular station', era: 'Shuttle Era', vehicle: 'Proton-K', actor: 'USSR', kind: 'first', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 8,
    description: 'The first space station assembled in orbit, built module by module over ten years and occupied for 12.5 of its 15 years — the prototype for the ISS.' },
  { date: '1990-04-24', title: 'Hubble deployed', era: 'Shuttle Era', vehicle: 'Space Shuttle Discovery', actor: 'NASA / ESA', kind: 'milestone', location: 'KSC LC-39B', lat: 28.61, lon: -80.60, impact: 9,
    description: 'An 11,110 kg telescope released at 540 km, peering up to ten billion years back in time. Five servicing missions over 25 years made it the most productive scientific instrument ever flown.' },
  { date: '1997-07-04', title: 'Mars Pathfinder and Sojourner', era: 'Shuttle Era', vehicle: 'Delta II', actor: 'NASA', kind: 'first', location: 'Cape Canaveral SLC-17B', lat: 28.50, lon: -80.60, impact: 7,
    description: 'Sojourner became the first successful planetary rover, rolling off a 100 kg lander that had bounced down in airbags — the template for every Mars mission since.' },
  { date: '1998-11-20', title: 'ISS Zarya launches', era: 'ISS Era', vehicle: 'Proton-K', actor: 'Roscosmos / NASA', kind: 'first', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 9,
    description: 'The 20 t control module began the largest object ever assembled in orbit — 100 m wide, 420 t, built from modules launched by five different rockets over 13 years.' },
  { date: '2000-11-02', title: 'Humanity never left orbit again', era: 'ISS Era', vehicle: 'Soyuz TM-31', actor: 'Expedition 1', kind: 'record', location: 'Baikonur', lat: 45.96, lon: 63.34, impact: 10,
    description: 'Three crew docked with the ISS and began a permanent human presence off Earth that has now run unbroken for more than a quarter of a century.' },
  { date: '2008-09-28', title: 'Falcon 1 reaches orbit', era: 'Commercial Age', vehicle: 'Falcon 1', actor: 'SpaceX', kind: 'first', location: 'Omelek Island, Kwajalein', lat: 9.05, lon: 167.74, impact: 9,
    description: 'On its fourth flight — after three explosions — the first privately funded liquid-fuelled rocket reached orbit, carrying a satellite and the ashes of an Apollo-era engineer.' },
  { date: '2010-06-04', title: 'Falcon 9 first flight', era: 'Commercial Age', vehicle: 'Falcon 9', actor: 'SpaceX', kind: 'first', location: 'Cape Canaveral SLC-40', lat: 28.50, lon: -80.60, impact: 9,
    description: 'The first nine-engine orbital rocket since Saturn reached orbit on its first attempt — and two years later became the first commercial vehicle to visit the ISS.' },
  { date: '2011-07-08', title: 'The Shuttle retires', era: 'Shuttle Era', vehicle: 'Space Shuttle Atlantis', actor: 'NASA', kind: 'milestone', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 7,
    description: 'The 135th and final Shuttle launch ended 30 years of reusable flight — and left America without a crewed launch capability for nine years.' },
  { date: '2015-12-21', title: 'The booster lands', era: 'New Space', vehicle: 'Falcon 9', actor: 'SpaceX', kind: 'first', location: 'Cape Canaveral SLC-40', lat: 28.50, lon: -80.60, impact: 10,
    description: 'After accelerating to Mach 6 and flipping around, a first stage restarted three engines and parked itself on a concrete pad. Rockets became reusable machines that afternoon.' },
  { date: '2018-02-06', title: 'Falcon Heavy and the Roadster', era: 'New Space', vehicle: 'Falcon Heavy', actor: 'SpaceX', kind: 'first', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 8,
    description: 'The most powerful rocket since Saturn V debuted by throwing a Tesla Roadster past Mars’ orbit on 27 engines — while its two side boosters landed side by side on adjacent pads.' },
  { date: '2020-05-30', title: 'First commercial crewed launch', era: 'New Space', vehicle: 'Falcon 9 / Crew Dragon', actor: 'SpaceX / NASA', kind: 'first', location: 'KSC LC-39A', lat: 28.61, lon: -80.60, impact: 9,
    description: 'Nine years after the Shuttle retired, astronauts launched from American soil again — on a commercially built and operated vehicle, the first of its kind.' },
  { date: '2020-11-23', title: 'Chang’e 5 brings home Moon rock', era: 'New Space', vehicle: 'Long March 5', actor: 'CNSA', kind: 'first', location: 'Wenchang', lat: 19.61, lon: 110.94, impact: 7,
    description: 'China’s first lunar sample return: 1,731 g of regolith, retrieved, launched from the Moon’s surface and delivered to Earth autonomously — the first new Moon samples in 44 years.' },
  { date: '2021-12-25', title: 'JWST unfolds', era: 'New Space', vehicle: 'Ariane 5', actor: 'ESA / NASA', kind: 'launch', location: 'Kourou ELA-3', lat: 5.24, lon: -52.77, impact: 9,
    description: 'The $10 billion telescope rode an Ariane 5 to a point 1.5 million km away, then unfolded 344 single-point failure mechanisms — every one of them worked.' },
  { date: '2023-04-20', title: 'Starship’s first flight', era: 'New Space', vehicle: 'Starship', actor: 'SpaceX', kind: 'failure', location: 'Starbase OLP-1, Texas', lat: 25.99, lon: -97.15, impact: 8,
    description: 'The largest rocket ever built cleared the tower on 33 engines, then tumbled and broke apart four minutes up. The pad survived; the flight data did not.' },
  { date: '2024-10-13', title: 'Mechazilla catches Super Heavy', era: 'New Space', vehicle: 'Super Heavy B12', actor: 'SpaceX', kind: 'first', location: 'Starbase OLP-1, Texas', lat: 25.99, lon: -97.15, impact: 10,
    description: 'A 70 m booster falling at the speed of sound was caught mid-air by two mechanical arms on the launch tower — the most audacious recovery ever attempted, on its first try.' },
  { date: '2025-01-16', title: 'New Glenn reaches orbit', era: 'New Space', vehicle: 'New Glenn', actor: 'Blue Origin', kind: 'first', location: 'Cape Canaveral LC-36', lat: 28.50, lon: -80.60, impact: 8,
    description: 'After 25 years of development, Blue Origin’s 98 m reusable orbital rocket flew — the first new American heavy-lift vehicle of the decade, named for the first American to orbit.' },
  { date: '2025-11-13', title: 'New Glenn lands its booster', era: 'New Space', vehicle: 'New Glenn', actor: 'Blue Origin', kind: 'first', location: 'Cape Canaveral LC-36', lat: 28.50, lon: -80.60, impact: 7,
    description: 'On only its second flight, New Glenn’s first stage touched down on a sea platform — making Blue Origin the second company to recover an orbital-class booster.' },
  { date: '2026-04-01', title: 'Artemis II: humans return to deep space', era: 'New Space', vehicle: 'SLS Block 1', actor: 'NASA', kind: 'first', location: 'KSC LC-39B', lat: 28.63, lon: -80.62, impact: 9,
    description: 'Four astronauts flew around the Moon — the first crewed lunar mission since 1972 — travelling about 700,000 miles in nine days and setting a new distance record for humans from Earth.' },
  { date: '2026-07-17', title: 'Vikram-1: India’s private sector reaches orbit', era: 'New Space', vehicle: 'Skyroot Vikram-1', actor: 'Skyroot Aerospace', kind: 'first', location: 'Satish Dhawan Space Centre', lat: 13.72, lon: 80.23, impact: 7,
    description: 'India’s first privately developed orbital rocket reached orbit on its maiden flight — the first orbital launch by an Indian company, and the first Vikram vehicle since the namesake lander.' },
  { date: '2026-09-05', title: 'Spectrum: Europe’s private sector reaches orbit', era: 'New Space', vehicle: 'Isar Aerospace Spectrum', actor: 'Isar Aerospace', kind: 'first', location: 'Andøya Spaceport, Norway', lat: 69.29, lon: 16.03, impact: 7,
    description: 'After months of delays, a German-built rocket launched from Norwegian soil and reached orbit — the first privately developed European rocket ever to do so, on only its second flight.' },
];

EVENTS.sort((a, b) => new Date(a.date) - new Date(b.date));

/* ============================================================
   ENGINES — the heart of the machine
   ============================================================ */
const ENGINES = [
  { name: 'F-1', rocket: 'Saturn V S-IC ×5', country: 'USA', propellant: 'LOX / RP-1', thrustSL: 6770, thrustVac: 7770, ispSL: 263, ispVac: 304, chamberPressure: 70, firstRun: '1959',
    note: 'Most powerful single-chamber liquid engine ever flown; each gulped 2,578 kg/s of propellant.' },
  { name: 'RS-25', rocket: 'Shuttle ×3 · SLS ×4', country: 'USA', propellant: 'LOX / LH2', thrustSL: 1860, thrustVac: 2279, ispSL: 366, ispVac: 452, chamberPressure: 206.4, firstRun: '1971',
    note: 'Highest-Isp staged-combustion engine ever flown; hydrogen turbopump alone makes 71,140 hp.' },
  { name: 'RD-170', rocket: 'Energia · Zenit', country: 'USSR', propellant: 'LOX / RG-1', thrustSL: 7250, thrustVac: 7900, ispSL: 309, ispVac: 337, chamberPressure: 245.2, firstRun: '1985',
    note: 'Most powerful rocket engine ever flown — one 192 MW turbopump feeding four chambers.' },
  { name: 'Raptor 3', rocket: 'Starship ×3–6 · Super Heavy ×33', country: 'USA', propellant: 'LOX / CH4', thrustSL: 2300, thrustVac: 2580, ispSL: 327, ispVac: 347, chamberPressure: 330, firstRun: '2016',
    note: 'Full-flow staged combustion at the highest chamber pressure of any engine ever flown (330 bar).' },
  { name: 'BE-4', rocket: 'Vulcan ×2 · New Glenn ×7', country: 'USA', propellant: 'LOX / CH4', thrustSL: 2460, thrustVac: null, ispSL: null, ispVac: 340, chamberPressure: 140, firstRun: '2024',
    note: 'First oxidizer-rich staged-combustion methalox engine to fly on an orbital rocket.' },
  { name: 'RD-180', rocket: 'Atlas III / Atlas V', country: 'Russia', propellant: 'LOX / RP-1', thrustSL: 3830, thrustVac: 4150, ispSL: 311, ispVac: 338, chamberPressure: 267, firstRun: '2000',
    note: 'Two chambers on one staged-combustion turbopump; a 100% flight record across a century of Atlas heritage.' },
  { name: 'Merlin 1D', rocket: 'Falcon 9 ×9 · Heavy ×27', country: 'USA', propellant: 'LOX / RP-1', thrustSL: 845, thrustVac: 981, ispSL: 282, ispVac: 311, chamberPressure: 97, firstRun: '2013',
    note: 'Highest thrust-to-weight of any operational engine (184:1); more than 700 have reached orbit.' },
  { name: 'RS-68A', rocket: 'Delta IV Heavy ×3', country: 'USA', propellant: 'LOX / LH2', thrustSL: 3137, thrustVac: 3560, ispSL: 365, ispVac: 412, chamberPressure: 102.6, firstRun: '2002',
    note: 'Deliberately simple and expendable — ablative nozzle, half the parts of an RS-25.' },
  { name: 'Vulcain 2.1', rocket: 'Ariane 6 core', country: 'France / ESA', propellant: 'LOX / LH2', thrustSL: null, thrustVac: 1359, ispSL: null, ispVac: 429, chamberPressure: 117.3, firstRun: '1996',
    note: 'The Ariane 6 variant’s 3D-printed nozzle cut parts count by 90% and cost by 40%.' },
  { name: 'LE-9', rocket: 'H3 first stage ×2–3', country: 'Japan', propellant: 'LOX / LH2', thrustSL: null, thrustVac: 1471, ispSL: null, ispVac: 426, chamberPressure: 100, firstRun: '2023',
    note: 'Expander-bleed cycle — no preburner at all; the largest engine of this cycle ever flown.' },
  { name: 'YF-100', rocket: 'Long March 5 / 6 / 7 / 8', country: 'China', propellant: 'LOX / RP-1', thrustSL: 1200, thrustVac: 1340, ispSL: 300, ispVac: 335, chamberPressure: 180, firstRun: '2015',
    note: 'China’s first staged-combustion engine; the basis of the entire new Long March generation.' },
  { name: 'RD-107A', rocket: 'Soyuz boosters ×4 + core', country: 'Russia', propellant: 'LOX / RG-1', thrustSL: 839, thrustVac: 1020, ispSL: 263, ispVac: 320, chamberPressure: 58.5, firstRun: '1957',
    note: 'In production for 69 years — the longest production run of any rocket engine in history.' },
  { name: 'J-2', rocket: 'Saturn V S-II ×5 · S-IVB ×1', country: 'USA', propellant: 'LOX / LH2', thrustSL: null, thrustVac: 1033, ispSL: null, ispVac: 421, chamberPressure: 52.6, firstRun: '1960',
    note: 'Restartable in space — the engine that pushed Apollo out of Earth orbit toward the Moon.' },
  { name: 'Rutherford', rocket: 'Electron ×9 + 1 vac', country: 'USA / NZ', propellant: 'LOX / RP-1', thrustSL: 24.9, thrustVac: 25.8, ispSL: 311, ispVac: 343, chamberPressure: null, firstRun: '2016',
    note: 'Electrically pumped: lithium-polymer batteries replace the entire turbopump gas system.' },
  { name: 'H-1', rocket: 'Saturn I / IB ×8', country: 'USA', propellant: 'LOX / RP-1', thrustSL: 900, thrustVac: null, ispSL: 255, ispVac: 289, chamberPressure: 48, firstRun: '1961',
    note: 'A 102.5:1 thrust-to-weight ratio that certified the Saturn dynasty on a budget.' },
  { name: 'Aestus', rocket: 'Ariane 5 EPS upper stage', country: 'Germany', propellant: 'N2O4 / MMH', thrustSL: null, thrustVac: 29.6, ispSL: null, ispVac: 324, chamberPressure: 11, firstRun: '1997',
    note: 'Pressure-fed with no turbopump; restartable up to eight times for precise orbit insertion.' },
  { name: 'A-4 engine', rocket: 'V-2', country: 'Germany', propellant: 'LOX / ethanol', thrustSL: 245, thrustVac: 284, ispSL: 204, ispVac: 204, chamberPressure: 15.2, firstRun: '1942',
    note: 'A steam-driven turbopump feeding a chamber at ~2,820 °C — the original rocket turbopump.' },
];

/* ============================================================
   SHOCK — numbers that don't compute
   ============================================================ */
const FACTS = [
  { id: 'saturn-v-energy', number: 170, unit: 'GW', era: 'Apollo', source: 'https://en.wikipedia.org/wiki/Rocketdyne_F-1',
    text: 'Igniting Saturn V’s five F-1s released chemical energy at roughly 170 GW — about 80 times the peak output of the Hoover Dam, concentrated in a 110 m tube.' },
  { id: 'saturn-flow', number: 12890, unit: 'kg/s', era: 'Apollo', source: 'https://en.wikipedia.org/wiki/Rocketdyne_F-1',
    text: 'The five F-1 engines together drank 12,890 kg of propellant every second — 4,880 litres of kerosene alone, enough to fill an Olympic swimming pool in eight and a half minutes.' },
  { id: 'saturn-drain', number: 2214, unit: 't', era: 'Apollo', source: 'https://en.wikipedia.org/wiki/Saturn_V',
    text: 'Saturn V’s 42 m first stage stood on the pad at 2,214 tonnes fully fuelled — and was drained completely dry in 165 seconds.' },
  { id: 'starship-thrust', number: 80.8, unit: 'MN', era: 'New Space', source: 'https://en.wikipedia.org/wiki/Super_Heavy_(rocket)',
    text: 'Starship’s 33 Raptors produce 80.8 MN at liftoff — more than twice Saturn V’s 34.5 MN. It is the most power ever controlled by a human-made machine.' },
  { id: 'orbit-speed', number: 7.8, unit: 'km/s', era: 'Physics', source: 'https://en.wikipedia.org/wiki/Low_Earth_orbit',
    text: 'To stay in orbit a rocket must reach 7.8 km/s — Mach 23, about 28,000 km/h — and it has roughly eight minutes to do it from a standing start.' },
  { id: 'tyranny', number: 20, unit: '×', era: 'Physics', source: 'https://en.wikipedia.org/wiki/Tsiolkovsky_rocket_equation',
    text: 'The rocket equation made flesh: Saturn V stood 2,822 tonnes on the pad to deliver 140 tonnes to orbit — roughly 20 kg of rocket and propellant for every 1 kg of payload.' },
  { id: 'falcon-reuse', number: 37, unit: 'flights', era: 'New Space', source: 'https://en.wikipedia.org/wiki/Template:Falcon_rocket_statistics',
    text: 'A single Falcon 9 booster has now flown 37 missions — a machine that cost tens of millions of dollars, reused like an airliner.' },
  { id: 'turnaround', number: 9, unit: 'days', era: 'New Space', source: 'https://en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters',
    text: 'Falcon 9 booster B1088 flew twice just 9 days, 3 hours and 39 minutes apart — the fastest turnaround of any orbital-class booster ever.' },
  { id: 'satellites', number: 16000, unit: 'active', era: 'Now', source: 'https://aerospaceglobalnews.com/news/how-many-satellites-orbiting-earth-2026',
    text: 'Around 16,000 functioning satellites now orbit Earth, of which roughly 11,150 belong to a single constellation: Starlink.' },
  { id: 'booster-fleet', number: 1000, unit: 'sats', era: 'New Space', source: 'https://en.wikipedia.org/wiki/List_of_Falcon_9_first-stage_boosters',
    text: 'Falcon 9 booster B1071 became the first to launch 1,000 cumulative spacecraft — a single first stage has now dispensed more satellites than most whole space programmes.' },
  { id: 'humans-speed', number: 39897, unit: 'km/h', era: 'Apollo', source: 'https://en.wikipedia.org/wiki/List_of_spaceflight_records',
    text: 'The fastest humans ever travelled were the Apollo 10 crew, re-entering at 39,897 km/h — a record unbroken for 57 years.' },
  { id: 'parker', number: 191.7, unit: 'km/s', era: 'Now', source: 'https://en.wikipedia.org/wiki/List_of_spaceflight_records',
    text: 'Parker Solar Probe is the fastest object ever built: 191.7 km/s relative to the Sun, fast enough to cross the Atlantic in 28 seconds.' },
  { id: 'cost-gap', number: 59700, unit: '$/kg', era: 'Shuttle → New Space', source: 'https://en.wikipedia.org/wiki/Space_Shuttle',
    text: 'The Space Shuttle cost about $59,700 to put one kilogramme in orbit. A reusable Falcon 9 lists at roughly $3,250 — an eighteenfold collapse in the price of escape.' },
  { id: 'presence', number: 9000, unit: 'days', era: 'ISS Era', source: 'https://en.wikipedia.org/wiki/International_Space_Station',
    text: 'Humans have lived continuously off Earth since 2 November 2000 — more than 9,000 unbroken days of occupation in orbit.' },
  { id: 'soyuz-flights', number: 1150, unit: 'launches', era: 'Workhorses', source: 'https://en.wikipedia.org/wiki/Soyuz_(rocket_family)',
    text: 'The Soyuz rocket family has flown more than 1,150 times — nobody has ever built a more reliable machine for leaving the planet.' },
  { id: 'turbopump', number: 257000, unit: 'hp', era: 'Soviet', source: 'https://en.wikipedia.org/wiki/RD-170',
    text: 'The RD-170’s single turbopump delivers 257,000 hp to four combustion chambers at once — the power of three nuclear icebreakers in one machine.' },
  { id: 'srb-vs-jet', number: 14700, unit: 'kN', era: 'Shuttle', source: 'https://en.wikipedia.org/wiki/Space_Shuttle_Solid_Rocket_Booster',
    text: 'One Shuttle solid booster pushed out 14,700 kN at liftoff — about 29 times the thrust of a GE90, the most powerful jet engine ever built.' },
  { id: 'water-deluge', number: 1100000, unit: 'L', era: 'Shuttle', source: 'https://en.wikipedia.org/wiki/Space_Shuttle',
    text: 'Every Shuttle launch sprayed 1.1 million litres of water under the stack at T-16 s — without it, the SRBs’ acoustic energy would have shaken the orbiter to pieces.' },
  { id: 'reentry', number: 1400, unit: '°C', era: 'Physics', source: 'https://en.wikipedia.org/wiki/SpaceX_Starship',
    text: 'A Starship re-entering at orbital speed generates plasma near 1,400 °C — hot enough to vaporise aluminium, deflected by 18,000 hexagonal silica tiles.' },
  { id: 'newhorizons', number: 16.26, unit: 'km/s', era: 'Golden Age', source: 'https://en.wikipedia.org/wiki/New_Horizons',
    text: 'New Horizons left Earth at 16.26 km/s — the fastest departure ever, crossing the Moon’s orbit in nine hours on a trip that took Apollo crews three days.' },
  { id: 'exhaust-vs-bullet', number: 2580, unit: 'm/s', era: 'Apollo', source: 'https://en.wikipedia.org/wiki/Rocketdyne_F-1',
    text: 'An F-1’s exhaust leaves the nozzle at about 2,580 m/s — nearly three times the muzzle velocity of a 5.56 mm rifle bullet.' },
];

/* ============================================================
   LIVE DATA — launches & industry pulse
   Sources: Spaceflight Now, SpaceX, NASA, ESA, planet4589 (McDowell)
   ============================================================ */
const LAUNCHES = [
  { date: '2026-09-28T12:15:00Z', windowConfirmed: false, rocket: 'Starship-Super Heavy (Ship 41 + Booster 21)', mission: 'Starship Flight 14', payload: '26 Starlink v3 satellites — first orbital deployment of v3', launchSite: 'Starbase OLP-2, Texas', agency: 'SpaceX', crew: false, crewNames: [], destination: 'LEO', notes: 'Planned first ORBITAL Starship flight; NET Sep 28, pending FAA approval.', likelihood: 'medium' },
  { date: '2026-10-01T15:10:00Z', windowConfirmed: true, rocket: 'Falcon 9 Block 5 (B1101, 3rd flight)', mission: 'NASA’s SpaceX Crew-13', payload: 'Crew Dragon C-213 “Grace”, 4 crew', launchSite: 'SLC-40, Cape Canaveral', agency: 'SpaceX / NASA', crew: true, crewNames: ['Jessica Watkins (NASA)', 'Luke Delaney (NASA)', 'Joshua Kutryk (CSA)', 'Sergey Teteryatnikov (Roscosmos)'], destination: 'ISS · Expedition 75/76', notes: 'Delayed from Sep 12 by a Dragon oxidiser leak.', likelihood: 'high' },
  { date: '2026-10-01T18:18:00Z', windowConfirmed: false, rocket: 'Falcon 9 Block 5', mission: 'Transporter-18', payload: 'Dedicated sun-synchronous-orbit rideshare', launchSite: 'SLC-4E, Vandenberg SFB', agency: 'SpaceX', crew: false, crewNames: [], destination: 'SSO', notes: 'Third SpaceX launch in ~24 hours.', likelihood: 'medium' },
  { date: '2026-10-02T03:53:00Z', windowConfirmed: true, rocket: 'Falcon Heavy (side boosters B1072, B1104)', mission: 'NROL-97', payload: 'Classified NRO payload', launchSite: 'KSC LC-39A', agency: 'SpaceX / NRO', crew: false, crewNames: [], destination: 'Classified (likely LEO)', notes: 'First NRO payload on Falcon Heavy; first NSSL Phase 3 Lane 2 mission.', likelihood: 'high' },
  { date: '2026-10-07', windowConfirmed: false, rocket: 'Ariane 64', mission: 'Amazon Leo (LE-04)', payload: 'Project Kuiper broadband satellites', launchSite: 'ELA-4, Kourou', agency: 'Arianespace', crew: false, crewNames: [], destination: 'LEO', notes: 'NET Oct 7.', likelihood: 'medium' },
  { date: '2026-10-10', windowConfirmed: false, rocket: 'Falcon 9 Block 5 (B1082, 25th flight)', mission: 'Starlink 15-25', payload: '27 Starlink V2 Mini satellites', launchSite: 'SLC-4E, Vandenberg SFB', agency: 'SpaceX', crew: false, crewNames: [], destination: 'LEO', notes: 'Launch time TBD; delayed from Sep 30.', likelihood: 'high' },
  { date: '2026-10-19T19:41:03Z', windowConfirmed: true, rocket: 'H3-24L', mission: 'Martian Moons eXploration (MMX)', payload: 'MMX spacecraft — Phobos sample return', launchSite: 'LA-Y2, Tanegashima', agency: 'JAXA / Mitsubishi Heavy Ind.', crew: false, crewNames: [], destination: 'Mars (Phobos)', notes: 'Planetary launch window; samples return ~FY2031.', likelihood: 'high' },
  { date: '2026-10', windowConfirmed: false, rocket: 'Falcon 9 Block 5', mission: 'CRS SpX-35', payload: 'Cargo Dragon to ISS', launchSite: 'SLC-40, Cape Canaveral', agency: 'SpaceX / NASA', crew: false, crewNames: [], destination: 'ISS', notes: 'NET October 2026.', likelihood: 'medium' },
  { date: '2026-10', windowConfirmed: false, rocket: 'Electron', mission: 'StriX Launch 12', payload: 'StriX SAR satellite for Synspective', launchSite: 'Launch Complex 1, Mahia', agency: 'Rocket Lab', crew: false, crewNames: [], destination: 'LEO', notes: 'NET October 2026.', likelihood: 'medium' },
  { date: '2026-10', windowConfirmed: false, rocket: 'Falcon 9 Block 5', mission: 'Bandwagon-5', payload: 'Dedicated mid-inclination rideshare', launchSite: 'SLC-40, Cape Canaveral', agency: 'SpaceX', crew: false, crewNames: [], destination: 'LEO (mid-inclination)', notes: 'NET October 2026.', likelihood: 'medium' },
  { date: '2026-11-19', windowConfirmed: false, rocket: 'Soyuz 2.1a / Fregat-M', mission: 'MKA Kinosputnik cluster', payload: 'Russian smallsat cluster', launchSite: 'Site 1S, Vostochny', agency: 'Roscosmos', crew: false, crewNames: [], destination: 'LEO', notes: 'NET Nov 19, 2026.', likelihood: 'medium' },
  { date: '2026-11-24T05:03:00Z', windowConfirmed: true, rocket: 'Soyuz 2.1b', mission: 'Progress MS-36', payload: 'ISS resupply cargo', launchSite: 'Site 31/6, Baikonur', agency: 'Roscosmos', crew: false, crewNames: [], destination: 'ISS', notes: 'Routine ISS cargo flight.', likelihood: 'high' },
  { date: '2026-11', windowConfirmed: false, rocket: 'Ariane 62', mission: 'MetOp-SG B1', payload: 'Second MetOp-SG weather satellite', launchSite: 'ELA-4, Kourou', agency: 'Arianespace / ESA / EUMETSAT', crew: false, crewNames: [], destination: 'LEO (polar)', notes: 'NET November 2026.', likelihood: 'medium' },
  { date: '2026-11', windowConfirmed: false, rocket: 'Falcon Heavy', mission: 'Griffin Mission One', payload: 'Intuitive Machines Griffin lunar lander (CLPS)', launchSite: 'KSC LC-39A', agency: 'SpaceX / Intuitive Machines / NASA', crew: false, crewNames: [], destination: 'Moon (south pole)', notes: 'NET November 2026; historically slip-prone.', likelihood: 'low' },
  { date: '2026-12', windowConfirmed: false, rocket: 'Proton-M / Briz-M', mission: 'Ekspress-AMU4', payload: 'Russian communications satellite', launchSite: 'Site 200/39, Baikonur', agency: 'Roscosmos', crew: false, crewNames: [], destination: 'GEO', notes: 'NET December 2026.', likelihood: 'medium' },
  { date: '2026-12', windowConfirmed: false, rocket: 'Falcon 9 Block 5', mission: 'CRS NG-25', payload: 'Cygnus cargo spacecraft to ISS', launchSite: 'SLC-40, Cape Canaveral', agency: 'SpaceX / Northrop Grumman / NASA', crew: false, crewNames: [], destination: 'ISS', notes: 'NET December 2026.', likelihood: 'medium' },
];

const STATS = [
  { id: 'launches-2025', value: 329, unit: 'attempts', decimals: 0, label: 'Orbital launch attempts in 2025', note: 'A record year — up roughly 25% on 2024.', source: 'planet4589.org' },
  { id: 'launches-ytd', value: 229, unit: 'YTD', decimals: 0, label: 'Orbital attempts so far in 2026', note: 'Live figure, through 23 Sep 2026.', source: 'wikipedia.org' },
  { id: 'falcon9-2025', value: 165, unit: 'launches', decimals: 0, label: 'Falcon 9 launches in a single year', note: 'The busiest rocket in history — ~51% of global launches.', source: 'aviationweek.com' },
  { id: 'soyuz-family', value: 1150, unit: 'launches', decimals: 0, label: 'Soyuz family launches, all time', note: 'The most-flown rocket family ever built.', source: 'wikipedia.org' },
  { id: 'booster-record', value: 37, unit: 'flights', decimals: 0, label: 'Most flights by a single booster', note: 'Falcon 9 B1067, as of Sep 2026.', source: 'wikipedia.org' },
  { id: 'active-sats', value: 16000, unit: 'active', decimals: 0, label: 'Functioning satellites in orbit', note: 'Of which roughly 11,150 are Starlink.', source: 'aerospaceglobalnews.com' },
  { id: 'humans-now', value: 10, unit: 'people', decimals: 0, label: 'Humans in space right now', note: '7 on ISS · 3 on Tiangong.', source: 'wikipedia.org' },
  { id: 'humans-ever', value: 781, unit: 'people', decimals: 0, label: 'Humans who have flown in space', note: 'In 65 years — fewer than fit on a single airliner.', source: 'wikipedia.org' },
];

/* ============================================================
   META
   ============================================================ */
const META = {
  pulseFoot: 'Figures compiled 27 Sep 2026 from Jonathan McDowell’s launch statistics, Wikipedia spaceflight records and ESA space-debris tracking. Live counters drift between updates.',
  launchNote: 'Manifest compiled 27 Sep 2026 from Spaceflight Now, SpaceX and agency sources. Dates marked NET are “no earlier than” planning targets and routinely slip — check the launch provider for the live window.',
  sources: 'NASA · ESA · JAXA · Roscosmos · CNSA · ISRO · SpaceX · ULA · Arianespace · Rocket Lab · Blue Origin · Wikipedia · Jonathan McDowell (planet4589) · Spaceflight Now',
  asOf: '2026-09-27',
};

export default { ROCKETS, rockets: ROCKETS, visuals: VISUALS, events: EVENTS, engines: ENGINES, facts: FACTS, launches: LAUNCHES, stats: STATS, meta: META };
